## right now I'm just trying to run whatever's in the dockerfile so you can enter a simple, single command:
#     `docker-compose up -d`
# and not require a ton of crazy cmd line crap.
version: "3"
services:
  generatedata:
    build: ""
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/generatedata
      - /home/app/generatedata/node_modules
