version: "3"
services:
  generatedata:
    context: ./client # added
    build: ..
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/generatedata
      - /home/app/generatedata/node_modules
  server:
    context: ./client # added
