version: "3"
services:

  webapp:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    expose:
      - 9000
    ports:
      - 9000:9000
    container_name: webapp
    volumes:
      - ./client:/home/app/generatedata/client
      - /home/app/generatedata/client/node_modules
    links:
      - server
    command: yarn webpackDev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    expose:
      - 3001
    ports:
      - 3001:3001
    restart: on-failure
    container_name: server
    volumes:
      - ./server:/home/app/generatedata/server
      - /home/app/generatedata/server/node_modules


    #    nginx:
#      image: nginx:latest
#      container_name: production_nginx
#      depends_on:
#        - web
#      volumes:
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      ports:
#        - 80:80
#        - 443:443

    ## this may be useful
#    environment:
#      - PGUSER=postgres
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGPASSWORD=
#      - PGPORT=5432
